1 - interface

    Uso do Tkinter para o GUI
        janela simples:
            2 - label para nome e idade
            2 - caixa de entry
            2 - botões Envio de dados | Retorno da gráfico


2- envio e retorno de dados

    por variavel/listas
        mais simples e sem muito esforço, só é útil para pouca informação e informação descartáveis



3- grafico atualizado - 2 tipos de dados utilizados

    Uso do Matplotlip
        Interface de colunas
        
